Update conditional-slack-message.yml

diff --git a/.github/workflows/conditional-slack-message.yml b/.github/workflows/conditional-slack-message.yml
--- a/.github/workflows/conditional-slack-message.yml
+++ b/.github/workflows/conditional-slack-message.yml
@@ -22,7 +22,6 @@ jobs:
         if: github.event_name == 'workflow_dispatch'
         run: |
           echo "DEV step"
-          exit 1
         
       - name: Push Schematics From Build Server - TEST
         id: build-test
@@ -35,6 +34,7 @@ jobs:
         if: github.event_name == 'schedule' && (startsWith(github.event.schedule, '*/15'))
         run: |
           echo "PROD step"
+          exit 1
 
       - name: Print slack message
         if: ${{ always() && ( steps.build-dev.outcome != 'failure' && steps.build-test != 'failure' && steps.build-prod.outcome != 'failure' ) }}
@@ -44,4 +44,4 @@ jobs:
       - name: Print slack message
         if: ${{ failure() && ( steps.build-dev.outcome == 'failure' || steps.build-test == 'failure' || steps.build-prod.outcome == 'failure' ) }}
         run: |
-          echo "Successful message"
+          echo "Failure message"
