Update delete-this.yml

diff --git a/.github/workflows/delete-this.yml b/.github/workflows/delete-this.yml
--- a/.github/workflows/delete-this.yml
+++ b/.github/workflows/delete-this.yml
@@ -18,8 +18,11 @@ jobs:
         run: |
              echo "## Test Results" >> $GITHUB_STEP_SUMMARY
              
-      - run: exit 1
+      - name: Fail step    
+        run: exit 1
         id: bad
         continue-on-error: true
-      - run: echo "OK"
-        if: job.steps.bad.status == failure()
+      #   id: bad
+      #   continue-on-error: true
+      # - run: echo "OK"
+      #   if: job.steps.bad.status == failure()
