Update project-cicd-1.yml

diff --git a/.github/workflows/project-cicd-1.yml b/.github/workflows/project-cicd-1.yml
--- a/.github/workflows/project-cicd-1.yml
+++ b/.github/workflows/project-cicd-1.yml
@@ -21,20 +21,22 @@ jobs:
         run: |
          echo "reviewed=true" >> $GITHUB_OUTPUT
          echo "cicd"
-         sleep 30
+         # sleep 30
+      - name: Dummy
+        run: echo "Run dummy"
 
   slack-success-failure:
     runs-on: ubuntu-latest
     needs: [cicd]
-    if: ${{ ( success('cicd') && needs.cicd.outputs.reviewed == 'true' ) || ( failure('cicd') && needs.cicd.outputs.reviewed == 'true' ) }}
+    if: ${{ ( success('cicd') && needs.cicd.outputs.reviewed == 'true' ) || ( failure('cicd') && needs.cicd.outputs.reviewed == 'true' ) || failure('cicd') && needs.cicd.outputs.reviewed != 'true' }}
     steps:
       - name: Print success or failure
         run: echo "Success or failure"
 
-  slack-rejected:
-    runs-on: ubuntu-latest
-    needs: [cicd]
-    if: ${{ failure('cicd') && needs.cicd.outputs.reviewed != 'true' }}
-    steps:
-       - name: Print rejected
-         run: echo "Rejected"
+  # slack-rejected:
+  #   runs-on: ubuntu-latest
+  #   needs: [cicd]
+  #   if: ${{ failure('cicd') && needs.cicd.outputs.reviewed != 'true' }}
+  #   steps:
+  #      - name: Print rejected
+  #        run: echo "Rejected"
