Update Test-echo.yml

diff --git a/.github/workflows/Test-echo.yml b/.github/workflows/Test-echo.yml
--- a/.github/workflows/Test-echo.yml
+++ b/.github/workflows/Test-echo.yml
@@ -20,8 +20,12 @@ jobs:
           echo "Commit alias is: $commit_alias"
           echo "$commit_alias"
           echo "Opening file"
-          test_file=$(cat $config_file)
-          echo "$test_file"
+          if [ -z "$config_file" ]; then
+            echo "Test txt/ file not found"
+            exit 1
+          fi
+          # test_file=$(cat $config_file)
+          # echo "cat $test_file"
           sed -i "s|baseUrl: 'https://onlineexpress-t.jlg.com'|baseUrl: '$commit_alias'|g" "$CONFIG_FILE"
 
       - name: Commit and push changes
